Vagrant::Config.run do |config|
  config.vm.box = "ruby_rvm"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.forward_port 80, 3001
  config.vm.network :bridged
#    config.vm.provision :puppet do |puppet|
#      puppet.module_path    = "puppet/modules"
#      puppet.manifests_path = "puppet/manifests"
#      puppet.manifest_file  = "site.pp"
#    end
end
