Vagrant.configure("2") do |config|

# config.vm.provision :puppet do |puppet|
#   puppet.manifests_path = "puppet/manifests"
#   puppet.manifest_file = "site.pp"
#   puppet.module_path = "puppet/modules"
# end

  config.vm.box = "precise64"
  config.vm.hostname = "cert"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.network :public_network
end
