Vagrant.configure("2") do |config|

 config.vm.provision :puppet do |puppet|
   puppet.manifests_path = "puppet/manifests"
   puppet.manifest_file = "site.pp"
   puppet.module_path = "puppet/modules"
 end

  config.vm.box = "centos6_puppet"
  config.vm.hostname = "cert"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box"
  config.vm.network :public_network
end
