# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "server-full"
#   config.vm.provider :virtualbox do |vb|
#     # Don't boot with headless mode
#     vb.gui = true

#	config.vm.share_folder "puppet", "/puppet", "puppet", :create => true
    
   config.vm.provision :puppet do |puppet|
     puppet.modules_path = "puppet/modules"
     puppet.manifests_path = "puppet/manifests"
     puppet.manifest_file  = "init.pp"
   end
end
