# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "server-full"
   config.vm.provider :virtualbox do |vb|
     # Don't boot with headless mode
     vb.gui = true
   end

   config.vm.provision :puppet do |puppet|
     config.vm.share_folder "puppet_mount", "c:\puppet", "puppet"
     puppet.modules_path = "puppet/modules"
     puppet.manifests_path = "manifests"
     puppet.manifest_file  = "init.pp"
   end
end
