Vagrant::Config.run do |config|
  config.vm.box = "centos6"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210.box"
  config.vm.host_name = "vtest1.forkedprocess.com"
  config.vm.forward_port 80, 3001
    config.vm.provision :puppet do |puppet|
      puppet.module_path    = "puppet/modules"
      puppet.manifests_path = "puppet/manifests"
      puppet.manifest_file  = "site.pp"
    end
end
