Vagrant::Config.run do |config|
  config.vm.box = "obsd"
  config.vm.forward_port 80, 3001
    config.vm.provision :puppet do |puppet|
      puppet.manifests_path = "puppet/manifests"
      puppet.module_path = "puppet/modules"
    end
end
